### ISSUE TITLE
Create installer.sh for HerbalDoc

### ISSUE THREAD

**Issue by aubrel** [meitar/flora-posidonia#6] opened 2017-11-02 17:26 UTC
Instead of listing out instructions on the product page for HerbalDoc, include instructions on GitHub README, and create an installer.sh for HerbalDoc on the storefront site.

**Comment by meitar** [comment] 2017-11-02 18:46
Duplicate of aubrel/herbaldoc#1.

**Closed by meitar** 2017-11-02 18:46 UTC
